
{ id: '909724632764125184',
  username: 'minorhash',
  displayName: 'マイナーはしゅ',
  photos:
   [ { value:
        'https://pbs.twimg.com/profile_images/910068041873899520/1VJDwdVJ_normal.jpg' } ],
  provider: 'twitter',
 _json:
   { id: 909724632764125200,
     id_str: '909724632764125184',
     name: 'マイナーはしゅ',
     screen_name: 'minorhash',
     location: '',
     description: 'node, pythonのapiとかやってます。',
     url: 'https://t.co/f2ivdT0dUd',
     entities: { url: [Object], description: [Object] },
     protected: false,
     followers_count: 94,
     friends_count: 276,
     listed_count: 2,
     created_at: 'Mon Sep 18 10:23:49 +0000 2017',
     favourites_count: 13,
     utc_offset: null,
     time_zone: null,
     geo_enabled: true,
     verified: false,
     statuses_count: 4404,
     lang: null,
     status:
      { created_at: 'Thu Jul 25 02:48:10 +0000 2019',
        id: 1154221776907325400,
        id_str: '1154221776907325441',
        text:
         '「jQuery 学習コース 初級編」コースを修了しました！ https://t.co/ZjloKRXwvk #Progate',
        truncated: false,
        entities: [Object],
        source:
         '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'ja' },
     contributors_enabled: false,
     is_translator: false,
     is_translation_enabled: false,
     profile_background_color: 'F5F8FA',
     profile_background_image_url: null,
     profile_background_image_url_https: null,
     profile_background_tile: false,
     profile_image_url:
      'http://pbs.twimg.com/profile_images/910068041873899520/1VJDwdVJ_normal.jpg',
     profile_image_url_https:
      'https://pbs.twimg.com/profile_images/910068041873899520/1VJDwdVJ_normal.jpg',
     profile_link_color: '1DA1F2',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     has_extended_profile: true,
     default_profile: true,
     default_profile_image: false,
     following: false,
     follow_request_sent: false,
     notifications: false,
     translator_type: 'none',
     suspended: false,
     needs_phone_verification: false },
  _accessLevel: 'read-write' }

